### ISSUE TITLE
Design a resilient CI/CD workflow

### ISSUE THREAD

**Issue by Szegoo** [RegionX-Labs/RegionX-Node#64]
Once #38 is complete we should try and come up with a more resilient workflow to be able to confidently ensure that everything is working as expected.

Things to add:
- [x] Block production check: added in #79 
- [x] crates.io dependency version check: added in #79 
- [x] Code coverage: added in #81
